export type ScheduleSpan = "single" | "double";

export type ScheduleBooking = {
  id: string;
  day: string;
  time: string;
  endTime: string;
  pitch: string;
  span: ScheduleSpan;
  halfSide?: 'A' | 'B';
  team1: string;
  team2?: string;
  locker1: string;
  locker2?: string;
  notes?: string;
};

export type ScheduleData = {
  weekLabel: string;
  weekNumber?: number;
  weekStartDate?: string;
  lastUpdated: string;
  bookings: ScheduleBooking[];
};

export const weekdayOrder = [
  "Monday",
  "Tuesday",
  "Wednesday",
  "Thursday",
  "Friday",
  "Saturday",
  "Sunday",
] as const;

export const defaultSchedule: ScheduleData = {
  weekLabel: "Exempelvecka (hög belastning)",
  weekNumber: 32,
  weekStartDate: "2026-08-03",
  lastUpdated: "2026-08-03T06:00:00.000Z",
  bookings: [
    {
      id: "monday-r1-0730",
      day: "Monday",
      time: "07:30",
      endTime: "08:30",
      pitch: "Ringvallen 1",
      span: "single",
      halfSide: "A",
      team1: "F17 Morning",
      team2: "Skill Session",
      locker1: "Room A",
      locker2: "Room B",
      notes: "Half A",
    },
    {
      id: "monday-r1-0845",
      day: "Monday",
      time: "08:45",
      endTime: "09:45",
      pitch: "Ringvallen 1",
      span: "single",
      halfSide: "B",
      team1: "P16 Academy",
      team2: "Press Drill",
      locker1: "Room C",
      locker2: "Room D",
      notes: "Half B",
    },
    {
      id: "monday-r1-1000",
      day: "Monday",
      time: "10:00",
      endTime: "11:00",
      pitch: "Ringvallen 1",
      span: "single",
      halfSide: "A",
      team1: "F15",
      team2: "Technique",
      locker1: "Room E",
      locker2: "Room F",
      notes: "Half A",
    },
    {
      id: "monday-r1-1115",
      day: "Monday",
      time: "11:15",
      endTime: "12:15",
      pitch: "Ringvallen 1",
      span: "single",
      halfSide: "B",
      team1: "P14",
      team2: "Passing",
      locker1: "Room G",
      locker2: "Room H",
      notes: "Half B",
    },
    {
      id: "monday-r1-1230",
      day: "Monday",
      time: "12:30",
      endTime: "14:00",
      pitch: "Ringvallen 1",
      span: "double",
      team1: "U19",
      team2: "Tactical Block",
      locker1: "Room I",
      locker2: "Room J",
      notes: "Full pitch prep",
    },
    {
      id: "monday-r1-1400",
      day: "Monday",
      time: "14:00",
      endTime: "15:00",
      pitch: "Ringvallen 1",
      span: "single",
      halfSide: "A",
      team1: "F13",
      team2: "Finishing",
      locker1: "Room K",
      locker2: "Room L",
      notes: "Half A",
    },
    {
      id: "monday-r1-1530",
      day: "Monday",
      time: "15:30",
      endTime: "16:30",
      pitch: "Ringvallen 1",
      span: "single",
      halfSide: "B",
      team1: "P13",
      team2: "Defending",
      locker1: "Room A",
      locker2: "Room B",
      notes: "Half B",
    },
    {
      id: "monday-r1-1700",
      day: "Monday",
      time: "17:00",
      endTime: "18:30",
      pitch: "Ringvallen 1",
      span: "double",
      team1: "U21",
      team2: "City United",
      locker1: "Room C",
      locker2: "Room D",
      notes: "Evening game",
    },
    {
      id: "monday-r1-1900",
      day: "Monday",
      time: "19:00",
      endTime: "20:00",
      pitch: "Ringvallen 1",
      span: "single",
      halfSide: "A",
      team1: "Ladies A",
      team2: "Recovery",
      locker1: "Room E",
      locker2: "Room F",
      notes: "Half A",
    },
    {
      id: "monday-r1-2030",
      day: "Monday",
      time: "20:30",
      endTime: "21:30",
      pitch: "Ringvallen 1",
      span: "single",
      halfSide: "B",
      team1: "Men B",
      team2: "Transition",
      locker1: "Room G",
      locker2: "Room H",
      notes: "Half B",
    },
    {
      id: "monday-r1-2145",
      day: "Monday",
      time: "21:45",
      endTime: "23:00",
      pitch: "Ringvallen 1",
      span: "double",
      team1: "Men A",
      team2: "Match Prep",
      locker1: "Room C",
      locker2: "Room D",
      notes: "Late full pitch",
    },
    {
      id: "tuesday-1900",
      day: "Tuesday",
      time: "19:00",
      endTime: "20:30",
      pitch: "Ringvallen 2",
      span: "double",
      team1: "North Stars",
      team2: "City United",
      locker1: "Room C",
      locker2: "Room D",
      notes: "Full pitch game",
    },
    {
      id: "wednesday-1700",
      day: "Wednesday",
      time: "17:00",
      endTime: "18:30",
      pitch: "Ringvallen 3",
      span: "double",
      team1: "Harbor FC",
      team2: "Lions",
      locker1: "Room E",
      locker2: "Room F",
    },
    {
      id: "thursday-1900",
      day: "Thursday",
      time: "19:00",
      endTime: "20:00",
      pitch: "Ringvallen 4",
      span: "single",
      team1: "Eagles",
      team2: "Storm",
      locker1: "Room G",
      locker2: "Room H",
    },
    {
      id: "saturday-1300",
      day: "Saturday",
      time: "13:00",
      endTime: "14:30",
      pitch: "Ringvallen 2",
      span: "double",
      team1: "Blue FC",
      team2: "Green FC",
      locker1: "Room I",
      locker2: "Room J",
    },
    {
      id: "sunday-1000",
      day: "Sunday",
      time: "10:00",
      endTime: "11:30",
      pitch: "Ringvallen 1",
      span: "single",
      team1: "Red Team",
      team2: "White Team",
      locker1: "Room K",
      locker2: "Room L",
    },
    {
      id: "friday-1830",
      day: "Friday",
      time: "18:30",
      endTime: "19:30",
      pitch: "Ringvallen 3",
      span: "single",
      halfSide: "B",
      team1: "F16",
      team2: "Positioning",
      locker1: "Room M",
      locker2: "Room N",
      notes: "Half B",
    },
    {
      id: "friday-2000",
      day: "Friday",
      time: "20:00",
      endTime: "21:30",
      pitch: "Ringvallen 4",
      span: "double",
      team1: "Senior Cup",
      team2: "Guest Team",
      locker1: "Room O",
      locker2: "Room P",
      notes: "Night game",
    },
  ],
};
